# Generated by Django 4.2.7 on 2023-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('paycheck_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paycheck_date', models.DateTimeField()),
            ],
        ),
    ]
