# Generated by Django 4.2.7 on 2023-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_userregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='captcha_solution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
