# Generated by Django 4.2.7 on 2023-12-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_userregistration_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('country', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.usermodel'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.usermodel'),
        ),
    ]
