# Generated by Django 4.2.7 on 2023-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_usermodel_delete_userregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
