# Generated by Django 4.2.7 on 2023-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_usermodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
